apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullnameOverride }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            {{- toYaml .Values.ports | nindent 10 }}

---
# Add routing rules for the existing Gateway included with Istio
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jackson-route-rules
spec:
  # https://istio.io/docs/reference/config/istio.networking.v1alpha3/#VirtualService
  gateways: # The default `mesh` value for when left blank is doesn't seem to propigate the rule properly. For now, always use a list of FQDN gateways
    - istio-autogenerated-k8s-ingress.istio-system.svc.cluster.local # must be FQDN if VirtualService in different NS than Gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            port:
              number: 8080
            host: jackson-api.default.svc.cluster.local
    - route: # This rule will pickup all other requests because it doesn't have a `match`
        - destination:
            port:
              number: 8080
            host: jackson-ui.default.svc.cluster.local
