apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.labelName }}
spec:
  selector:
    app: {{ .Values.appName }} # Deployment name tag
  ports:
  - name: http
    port: {{ .Values.service.port }}

{{- if .Values.enableDestinationRule }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.labelName }}
spec:
  host: "{{ .Values.service.name }}.{{ .Values.service.namespace }}.svc.cluster.local"
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary
{{- end }}

{{- if .Values.enableVirtualService }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service.name }}
spec:
    # https://istio.io/docs/reference/config/istio.networking.v1alpha3/#VirtualService
  gateways: # The default `mesh` value for when left blank is doesn't seem to propigate the rule properly. For now, always use a list of FQDN gateways
    - istio-autogenerated-k8s-ingress.istio-system.svc.cluster.local # must be FQDN if VirtualService in different NS than Gateway
  hosts:
    # Services in Kubernetes expose their endpoint using a common DNS pattern.
    # It looks like: <Service Name>.<Namespace Name>.svc.cluster.local
    # if not a FQDN then Istio assumes default namespace
    - "{{ .Values.service.name }}.{{ .Values.service.namespace }}.svc.cluster.local"
  http:
  - route:
    - destination:
        host: "{{ .Values.service.name }}.{{ .Values.service.namespace }}.svc.cluster.local"
        subset: stable
        port: 
          number: {{ .Values.service.port }}
      weight: {{ .Values.service.stableWeight}}
    - destination:
        host: "{{ .Values.service.name }}.{{ .Values.service.namespace }}.svc.cluster.local"
        subset: canary
        port: 
          number: {{ .Values.service.port }}
      weight: {{ .Values.service.canaryWeight}}
{{- end }}
---
# Add routing rules for the existing Gateway included with Istio
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jackson-route-rules
spec:
  # https://istio.io/docs/reference/config/istio.networking.v1alpha3/#VirtualService
  gateways: # The default `mesh` value for when left blank is doesn't seem to propigate the rule properly. For now, always use a list of FQDN gateways
    - istio-autogenerated-k8s-ingress.istio-system.svc.cluster.local # must be FQDN if VirtualService in different NS than Gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            port:
              number: 8080
            host: jackson-api.default.svc.cluster.local
    - route: # This rule will pickup all other requests because it doesn't have a `match`
        - destination:
            port:
              number: 8080
            host: jackson-ui.default.svc.cluster.local